# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0

    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: destroyed-symlinks
    -   id: trailing-whitespace

-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0

    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy

exclude: |
  (?x)
  ^
  ( vectorscan-rs-sys/vectorscan\.patch
  | vectorscan-rs-sys/src/bindings\.rs
  ) $
